# Generated by Django 5.1.5 on 2025-02-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_subtitulo_alter_post_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='subtitulo',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
